# Generated by Django 4.2.7 on 2026-01-07 11:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Numéro WhatsApp au format E.164', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Format E.164 requis (ex: +221771234567)', regex='^\\+[1-9]\\d{1,14}$')])),
                ('role', models.CharField(choices=[('OWNER', 'Propriétaire'), ('DRIVER', 'Chauffeur')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborations_declared_count', models.IntegerField(default=0)),
                ('last_declaration_at', models.DateTimeField(blank=True, null=True)),
                ('abuse_flags', models.JSONField(default=dict, help_text="Flags d'abus détectés (silencieux, non-bloquant)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='core.user')),
            ],
            options={
                'db_table': 'owner_profiles',
            },
        ),
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('DECLARED', 'Déclarée'), ('PENDING_CONFIRMATION', 'En attente de confirmation'), ('CONFIRMED', 'Confirmée'), ('ELIGIBLE_FOR_RATING', 'Éligible pour évaluation'), ('RATED', 'Évaluée')], default='DECLARED', max_length=30)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_as_driver', to='core.user')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_as_owner', to='core.user')),
            ],
            options={
                'db_table': 'collaborations',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_punctuality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Score ponctualité (1-5)')),
                ('score_vehicle_respect', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Score respect véhicule (1-5)')),
                ('score_client_relation', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Score relation client (1-5)')),
                ('score_reliability', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Score fiabilité globale (1-5)')),
                ('comment_raw', models.TextField(blank=True, help_text='Commentaire brut original (jamais exposé publiquement)', null=True)),
                ('comment_sanitized', models.TextField(blank=True, help_text='Commentaire nettoyé par LLM', null=True)),
                ('comment_published', models.TextField(blank=True, help_text='Commentaire publié (peut être NULL si rejeté 3 fois)', null=True)),
                ('sanitization_rejections_count', models.IntegerField(default=0, help_text='Nombre de rejets de sanitisation (max 3)')),
                ('is_published', models.BooleanField(default=False)),
                ('driver_response', models.TextField(blank=True, null=True)),
                ('driver_response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('collaboration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='core.collaboration')),
            ],
            options={
                'db_table': 'ratings',
                'indexes': [models.Index(fields=['collaboration'], name='ratings_collabo_78c27e_idx'), models.Index(fields=['is_published'], name='ratings_is_publ_c7d872_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text="Nom d'affichage optionnel", max_length=100, null=True)),
                ('permit_hash', models.CharField(help_text='SHA-256 hash du permis normalisé + salt', max_length=64, unique=True)),
                ('permit_salt', models.CharField(help_text='Salt unique pour le hachage (jamais exposé)', max_length=64)),
                ('identity_locked', models.BooleanField(default=False, help_text='Une fois True, ne peut jamais revenir à False')),
                ('identity_locked_at', models.DateTimeField(blank=True, null=True)),
                ('reputation_cached', models.JSONField(blank=True, help_text='Cache de réputation calculée', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='core.user')),
            ],
            options={
                'db_table': 'driver_profiles',
                'indexes': [models.Index(fields=['permit_hash'], name='driver_prof_permit__ea6190_idx'), models.Index(fields=['identity_locked'], name='driver_prof_identit_2a2249_idx'), models.Index(fields=['permit_hash', 'permit_salt'], name='driver_prof_permit__f14c66_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(max_length=100)),
                ('temp_data', models.JSONField(default=dict)),
                ('expected_input_type', models.CharField(choices=[('MENU_CHOICE', 'Choix menu'), ('CONFIRMATION', 'Confirmation Oui/Non'), ('PHONE_NUMBER', 'Numéro téléphone'), ('PERMIT_NUMBER', 'Numéro permis'), ('SANITIZED_TEXT', 'Texte à sanitiser'), ('SCORE_RATING', 'Score évaluation')], max_length=20)),
                ('allowed_values', models.JSONField(blank=True, null=True)),
                ('invalid_input_count', models.IntegerField(default=0)),
                ('behavior_on_invalid_input', models.CharField(choices=[('RETRY_SAME_STATE', 'Réessayer même état'), ('RETURN_TO_PREVIOUS', 'Retour état précédent'), ('RETURN_TO_MAIN_MENU', 'Retour menu principal')], max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states', to='core.user')),
            ],
            options={
                'db_table': 'conversation_states',
                'indexes': [models.Index(fields=['user'], name='conversatio_user_id_29f870_idx'), models.Index(fields=['expires_at'], name='conversatio_expires_df9ece_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PROFILE_CREATION', 'Création profil'), ('COLLABORATION_CONFIRMATION', 'Confirmation collaboration'), ('RATING_PUBLICATION', 'Publication évaluation')], max_length=30)),
                ('context', models.JSONField(blank=True, help_text="Contexte de l'action (collaboration_id, rating_id, etc.)", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='core.user')),
            ],
            options={
                'db_table': 'consent_logs',
                'indexes': [models.Index(fields=['user', 'action', 'timestamp'], name='consent_log_user_id_a955de_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['owner', 'driver'], name='collaborati_owner_i_b4d667_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['state'], name='collaborati_state_1e7a30_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboration',
            index=models.Index(fields=['driver', 'state'], name='collaborati_driver__f81564_idx'),
        ),
        migrations.AddConstraint(
            model_name='collaboration',
            constraint=models.CheckConstraint(check=models.Q(('owner', models.F('driver')), _negated=True), name='owner_cannot_be_driver'),
        ),
    ]
