# Generated by Django 4.2.7 on 2026-01-24 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Identifiant utilisateur (WhatsApp E.164 ou Telegram tg:<chat_id>)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Identifiant invalide. WhatsApp: +221771234567, Telegram: tg:123456789', regex='^(\\+[1-9]\\d{1,14}|tg:\\d+)$')]),
        ),
    ]
