# Generated by Django 4.2.7 on 2026-01-24 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trust_signals'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('reported_phone_e164', models.CharField(blank=True, help_text='Numéro déclaré (enrichissement, pas identifiant primaire)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Format E.164 requis (ex: +22501020304)', regex='^\\+[1-9]\\d{1,14}$')])),
                ('duration_choice', models.IntegerField(choices=[(1, 'Moins d’1 mois'), (2, '1 à 3 mois'), (3, 'Plus de 3 mois')])),
                ('main_problem_code', models.IntegerField(choices=[(1, 'Versements journaliers irréguliers'), (2, 'Mensonges / manque de transparence'), (3, 'Mauvaise gestion du véhicule'), (4, 'Refus de consignes'), (5, 'Problèmes avec la police'), (6, 'Abandon / injoignable'), (7, 'Autre')])),
                ('main_problem_other_text', models.TextField(blank=True, null=True)),
                ('severity', models.IntegerField(choices=[(1, 'Mineur'), (2, 'Sérieux'), (3, 'Grave')])),
                ('recommend', models.BooleanField()),
                ('legal_confirmed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='core.driverprofile')),
                ('owner', models.ForeignKey(help_text='Propriétaire qui signale (channel-agnostic via User.phone_number)', on_delete=django.db.models.deletion.CASCADE, related_name='driver_signals', to='core.user')),
            ],
            options={
                'db_table': 'driver_signals',
                'indexes': [models.Index(fields=['permit_fingerprint', 'created_at'], name='driver_sign_permit__603d48_idx'), models.Index(fields=['owner', 'created_at'], name='driver_sign_owner_i_9648dc_idx'), models.Index(fields=['severity'], name='driver_sign_severit_373f46_idx'), models.Index(fields=['recommend'], name='driver_sign_recomme_0b2d5d_idx')],
            },
        ),
    ]
